AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fast Food Authentication

Globals:
  Function:
    Timeout: 3

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authentication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:ListUsers
              Resource: !GetAtt CognitoUserPool.Arn
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          CLIENT_ID: !Ref CognitoUserPoolClient
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post
        GetUser:
          Type: Api
          Properties:
            Path: /user/{cpf}
            Method: get

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AuthUserPool
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: cpf
          AttributeDataType: String
          Mutable: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: AuthClient
      GenerateSecret: false

Outputs:
  AuthenticationApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  AuthenticationFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AuthenticationFunction.Arn